name: Publish Python Package

on:
  push:
    tags:
      - "v*"  # Dispara o workflow ao criar uma tag iniciando com "v"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout do código
      - name: Checkout code
        uses: actions/checkout@v3

      # Configurar a versão do Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      # Instalar dependências para build
      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      # Construir o pacote usando `py -m build`
      - name: Build package
        run: python -m build

      # Publicar no PyPI
      - name: Publish to PyPI
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: python -m twine upload --repository pypi dist/*
